### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by AndyIsHereBoi** [Scubakay/autorelog#12]
Does this still keep attempting to reconnect even after the client reconnected once? And if it fails to connect does it try again or just end?

**Comment by Scubakay** [comment]
It tries reconnecting every 30 seconds until it works, or until you click away from the disconnect screen. I have an issue somewhere (#11) to make the timer configurable.

**Comment by Scubakay** [comment]
Interesting. I'll look into that when I have the time!
