### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by swiftpwns** [Scubakay/autorelog#17]
Doesn't work, mc crashes when trying to launch, the only other mods I have is fabric and fabric api. I tried with both older and newer fabric versions.

**Comment by swiftpwns** [comment]
I dont need help anymore thanks

**Comment by swiftpwns** [comment]
Oh wait this is for autorelog? I also dont need help for that anymore but I
can give you the crash log sometime for that, im using autoteconnect now,
your mod needs to be manually activate each time, autoteconnect doesnt have
that shortcoming

**Comment by Scubakay** [comment]
There's a pull request from someone that will add a feature to detect AFK to activate. Will probably be adding that soon 👍
