### ISSUE TITLE
add modmenu config support

### ISSUE THREAD

**Issue by alien-sunset** [Scubakay/autorelog#22]
what it says on the tin: allow players to config the mod using an in game gui accessible via modmenu or some other config lib.

**Comment by Scubakay** [comment]
This is certainly something I can look into at some point!

**Comment by Scubakay** [comment]
Mod Menu support has been added in version 0.1.0+1.21!

Used MidnightLib for it, so no new dependencies, but the config file is now json, so you will have to reconfigure the mod.
