### ISSUE TITLE
Server Throttling

### ISSUE THREAD

**Issue by FuriousFire898** [Scubakay/autorelog#30]
It ends up in a loop of consant incapable relogs, this may be due to the server but still maybe if it would allow you to end it or atleast be staggered more.
The server i tried to use on just ended up refusing it out right every log and i had to restart minecraft

**Comment by Scubakay** [comment]
Depending on what version of Minecraft you are on, you can change `interval` in the config to a higher number. This will make AutoRelog take longer before attempting to reconnect, and in between attempts. The default is 30 seconds.
You can also set `maxAttempts`, which will limit the amount of reconnection attempts AutoRelog will make.
I'll be updating to 1.21.1 today, but this mod will not be backward compatible. (new features won't be added to older versions)
