### ISSUE TITLE
Can you make it so it autoreconnects by default ?

### ISSUE THREAD

**Issue by AdielHub** [Scubakay/autorelog#31]
Or add a config for it ?

If i'm at my computer i won't need to auto reconnect after 60 seconds i'll just either open another server, quit the game or reconnect myself

However, if you're afk you always wanna get reconnected

**Comment by Scubakay** [comment]
This was added in 0.0.7+1.20.6 and is turned on by default.
If you are on 1.21 you can use ModMenu to configure this.
