### ISSUE TITLE
closure

### ISSUE THREAD

**Issue by newmoonTW** [Scubakay/autorelog#32]
Sorry my English is not good enough. Sometimes I don’t need automatic connection. How can I turn off automatic connection freely?

**Comment by Scubakay** [comment]
You can turn off automatic connection in the config. I'm not sure if you'd need to change this setting in game.

I wrote a command `/autorelog mode` to switch in game, but Midnightlib doesn't want to save it to config somehow. 

What is the usecase for this feature?

**Comment by Scubakay** [comment]
I clearly wasn't thinking yesterday. You can turn off automatic mode through Mod Menu.
